"""create user table

Revision ID: 285343f3cabf
Revises: 
Create Date: 2025-07-05 18:55:53.600239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285343f3cabf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=64), nullable=False),
    sa.Column('attendance', sa.String(length=64), nullable=False),
    sa.Column('guestCount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fullname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
